layout_spectrum: 0.6578947
color:
  saturation: 1
  brandStrength: 0.1811139
  lightness: 1
  rhythmicContrast: 0
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 1
name: Etchnsketch
