name: Etch n sketch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07673
title: Etch n Sketch Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#ebd2b3'
    - '#8f764c'
    - '#6c4f27'
    - '#ccb38a'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
